;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="NPCEvent.Dialogue.End",DevComment="")
+GameplayTagList=(Tag="NPCEvent.Dialogue.Start",DevComment="")
+GameplayTagList=(Tag="NPCEvent.Match.Requested",DevComment="")
+GameplayTagList=(Tag="SmartObject.Activity.Idle",DevComment="")
+GameplayTagList=(Tag="SmartObject.Activity.Sit",DevComment="")
+GameplayTagList=(Tag="SmartObject.User",DevComment="")
+GameplayTagList=(Tag="SmartObject.User.NPC",DevComment="")
+GameplayTagList=(Tag="SmartObject.User.Player",DevComment="")
+GameplayTagList=(Tag="UI.Stack.InGame",DevComment="")
+GameplayTagList=(Tag="UI.Stack.Modal",DevComment="")
+GameplayTagList=(Tag="UI.Stack.Title",DevComment="")

